base_yml: configs/voxel_head/voxel_base.yml
data:
  training:
    class_name: Mug
    voxel_trans_noise_max: 10
    voxel_size_noise_max: [5, 5, 3]
  validation:
    class_name: Mug
    voxel_trans_noise_max: 10
    voxel_size_noise_max: [5, 5, 3]
model:
  param_head:
    in_chan: 757
    out_chan: 9 # dim of params
  pos_head:
    in_chan: 757
  ori_head:
    in_chan: 757
  cls_name: Mug